/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Take01;
import java.util.Random;

/**
 *
 * @author hp
 */
public class MainFrame extends javax.swing.JFrame {
    static Random rand;
    int value1, value2, value3;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Roll");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Double Dice");

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(231, 231, 231))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/none.png"))); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/none.png"))); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/none.png"))); // NOI18N
        
        value1=rand.nextInt(6)+1;
        value2=rand.nextInt(6)+1;
        value3=rand.nextInt(6)+1;
        
        //if two dices have 6 then third dice shows up
        if(value1==6 && value2==6){
            switch(value3){
                case 1:
                    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/one.png"))); // NOI18N
                    break;
                case 2:
                    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/two.png"))); // NOI18N
                    break;
                case 3:
                    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/three.png"))); // NOI18N
                    break;
                case 4:
                    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/four.png"))); // NOI18N
                    break;
                case 5:
                    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/five.png"))); // NOI18N
                    break;
                case 6:
                    do{
                        value3=rand.nextInt(6)+1;
                    }
                    while(value3==6);

                    switch(value3){
                        case 1:
                            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/one.png"))); // NOI18N
                            break;
                        case 2:
                            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/two.png"))); // NOI18N
                            break;
                        case 3:
                            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/three.png"))); // NOI18N
                            break;
                        case 4:
                            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/four.png"))); // NOI18N
                            break;
                        case 5:
                            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/five.png"))); // NOI18N
                            break;
                        default:
                            System.out.println("Error in switch after do while_value3");
                    }
                default:
                    System.out.println("Error in switch_value3:"+value3);
            }
        }
        switch(value1){
            case 1:
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/one.png"))); // NOI18N
                break;
            case 2:
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/two.png"))); // NOI18N
                break;
            case 3:
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/three.png"))); // NOI18N
                break;
            case 4:
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/four.png"))); // NOI18N
                break;
            case 5:
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/five.png"))); // NOI18N
                break;
            case 6:
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/six.png"))); // NOI18N
                break;
            default:
                System.out.println("Error in switch_value1:"+value1);
        }
        switch(value2){
            case 1:
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/one.png"))); // NOI18N
                break;
            case 2:
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/two.png"))); // NOI18N
                break;
            case 3:
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/three.png"))); // NOI18N
                break;
            case 4:
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/four.png"))); // NOI18N
                break;
            case 5:
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/five.png"))); // NOI18N
                break;
            case 6:
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/six.png"))); // NOI18N
                break;
            default:
                System.out.println("Error in switch_value2:"+value2);
        }
        
        //for showing large value dice first
//        if(value1>value2){
//            switch(value1){
//                case 1:
//                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/one.png"))); // NOI18N
//                    break;
//                case 2:
//                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/two.png"))); // NOI18N
//                    break;
//                case 3:
//                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/three.png"))); // NOI18N
//                    break;
//                case 4:
//                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/four.png"))); // NOI18N
//                    break;
//                case 5:
//                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/five.png"))); // NOI18N
//                    break;
//                case 6:
//                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/six.png"))); // NOI18N
//                    break;
//            }
//            switch(value2){
//                case 1:
//                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/one.png"))); // NOI18N
//                    break;
//                case 2:
//                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/two.png"))); // NOI18N
//                    break;
//                case 3:
//                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/three.png"))); // NOI18N
//                    break;
//                case 4:
//                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/four.png"))); // NOI18N
//                    break;
//                case 5:
//                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/five.png"))); // NOI18N
//                    break;
//                case 6:
//                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/six.png"))); // NOI18N
//                    break;
//            }
//        }
//        else{
//            switch(value2){
//                case 1:
//                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/one.png"))); // NOI18N
//                    break;
//                case 2:
//                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/two.png"))); // NOI18N
//                    break;
//                case 3:
//                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/three.png"))); // NOI18N
//                    break;
//                case 4:
//                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/four.png"))); // NOI18N
//                    break;
//                case 5:
//                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/five.png"))); // NOI18N
//                    break;
//                case 6:
//                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/six.png"))); // NOI18N
//                    break;
//            }
//            switch(value1){
//                case 1:
//                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/one.png"))); // NOI18N
//                    break;
//                case 2:
//                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/two.png"))); // NOI18N
//                    break;
//                case 3:
//                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/three.png"))); // NOI18N
//                    break;
//                case 4:
//                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/four.png"))); // NOI18N
//                    break;
//                case 5:
//                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/five.png"))); // NOI18N
//                    break;
//                case 6:
//                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/six.png"))); // NOI18N
//                    break;
//            }
//        }
          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/none.png"))); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/none.png"))); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Take01/none.png"))); // NOI18N
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        rand=new Random();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
